name: Build Application and Make Release

on:
  push:
    tags:
      - "*"

permissions: {}

jobs:
  build_release:
    name: Build Release
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      # Required for Azure Trusted Signing
      id-token: write
      # Required for vcpkg binary cache
      packages: write
    with:
      build-type: Release
      environment: Release
    secrets: inherit

  create_release:
    needs: build_release
    permissions:
      contents: write
    runs-on: ubuntu-slim
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: "true"
          path: "AmethystLauncher-source"
      - name: Download artifacts
        uses: actions/download-artifact@v7
      - name: Grab and store version
        run: |
          tag_name=$(echo ${{ github.ref }} | grep -oE "[^/]+$")
          echo "VERSION=$tag_name" >> $GITHUB_ENV
      - name: Package artifacts properly
        run: |
          mv ${{ github.workspace }}/AmethystLauncher-source AmethystLauncher-${{ env.VERSION }}
          mv AmethystLauncher-Linux-Qt6-Portable*/AmethystLauncher-portable.tar.gz AmethystLauncher-Linux-Qt6-Portable-${{ env.VERSION }}.tar.gz
          mv AmethystLauncher-Linux-aarch64-Qt6-Portable*/AmethystLauncher-portable.tar.gz AmethystLauncher-Linux-aarch64-Qt6-Portable-${{ env.VERSION }}.tar.gz
          mv AmethystLauncher-*.AppImage/AmethystLauncher-*-x86_64.AppImage AmethystLauncher-Linux-x86_64.AppImage
          mv AmethystLauncher-*.AppImage.zsync/AmethystLauncher-*-x86_64.AppImage.zsync AmethystLauncher-Linux-x86_64.AppImage.zsync
          mv AmethystLauncher-*.AppImage/AmethystLauncher-*-aarch64.AppImage AmethystLauncher-Linux-aarch64.AppImage
          mv AmethystLauncher-*.AppImage.zsync/AmethystLauncher-*-aarch64.AppImage.zsync AmethystLauncher-Linux-aarch64.AppImage.zsync
          mv AmethystLauncher-macOS*/AmethystLauncher.zip AmethystLauncher-macOS-${{ env.VERSION }}.zip

          tar --exclude='.git' -czf AmethystLauncher-${{ env.VERSION }}.tar.gz AmethystLauncher-${{ env.VERSION }}

          for d in AmethystLauncher-Windows-MSVC*; do
            cd "${d}" || continue
            LEGACY="$(echo -n ${d} | grep -o Legacy || true)"
            ARM64="$(echo -n ${d} | grep -o arm64 || true)"
            INST="$(echo -n ${d} | grep -o Setup || true)"
            PORT="$(echo -n ${d} | grep -o Portable || true)"
            NAME="AmethystLauncher-Windows-MSVC"
            test -z "${LEGACY}" || NAME="${NAME}-Legacy"
            test -z "${ARM64}" || NAME="${NAME}-arm64"
            test -z "${PORT}" || NAME="${NAME}-Portable"
            test -z "${INST}" || mv AmethystLauncher-*.exe ../${NAME}-Setup-${{ env.VERSION }}.exe
            test -n "${INST}" || zip -r -9 "../${NAME}-${{ env.VERSION }}.zip" *
            cd ..
          done

          for d in AmethystLauncher-Windows-MinGW-w64*; do
            cd "${d}" || continue
            INST="$(echo -n ${d} | grep -o Setup || true)"
            PORT="$(echo -n ${d} | grep -o Portable || true)"
            NAME="AmethystLauncher-Windows-MinGW-w64"
            test -z "${PORT}" || NAME="${NAME}-Portable"
            test -z "${INST}" || mv AmethystLauncher-*.exe ../${NAME}-Setup-${{ env.VERSION }}.exe
            test -n "${INST}" || zip -r -9 "../${NAME}-${{ env.VERSION }}.zip" *
            cd ..
          done

          for d in AmethystLauncher-Windows-MinGW-arm64*; do
            cd "${d}" || continue
            INST="$(echo -n ${d} | grep -o Setup || true)"
            PORT="$(echo -n ${d} | grep -o Portable || true)"
            NAME="AmethystLauncher-Windows-MinGW-arm64"
            test -z "${PORT}" || NAME="${NAME}-Portable"
            test -z "${INST}" || mv AmethystLauncher-*.exe ../${NAME}-Setup-${{ env.VERSION }}.exe
            test -n "${INST}" || zip -r -9 "../${NAME}-${{ env.VERSION }}.zip" *
            cd ..
          done

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          name: Amethyst Launcher ${{ env.VERSION }}
          draft: true
          prerelease: false
          fail_on_unmatched_files: true
          files: |
            AmethystLauncher-Linux-x86_64.AppImage
            AmethystLauncher-Linux-x86_64.AppImage.zsync
            AmethystLauncher-Linux-aarch64.AppImage
            AmethystLauncher-Linux-aarch64.AppImage.zsync
            AmethystLauncher-Linux-Qt6-Portable-${{ env.VERSION }}.tar.gz
            AmethystLauncher-Linux-aarch64-Qt6-Portable-${{ env.VERSION }}.tar.gz
            AmethystLauncher-Windows-MinGW-w64-${{ env.VERSION }}.zip
            AmethystLauncher-Windows-MinGW-w64-Portable-${{ env.VERSION }}.zip
            AmethystLauncher-Windows-MinGW-w64-Setup-${{ env.VERSION }}.exe
            AmethystLauncher-Windows-MinGW-arm64-${{ env.VERSION }}.zip
            AmethystLauncher-Windows-MinGW-arm64-Portable-${{ env.VERSION }}.zip
            AmethystLauncher-Windows-MinGW-arm64-Setup-${{ env.VERSION }}.exe
            AmethystLauncher-Windows-MSVC-arm64-${{ env.VERSION }}.zip
            AmethystLauncher-Windows-MSVC-arm64-Portable-${{ env.VERSION }}.zip
            AmethystLauncher-Windows-MSVC-arm64-Setup-${{ env.VERSION }}.exe
            AmethystLauncher-Windows-MSVC-${{ env.VERSION }}.zip
            AmethystLauncher-Windows-MSVC-Portable-${{ env.VERSION }}.zip
            AmethystLauncher-Windows-MSVC-Setup-${{ env.VERSION }}.exe
            AmethystLauncher-macOS-${{ env.VERSION }}.zip
            AmethystLauncher-${{ env.VERSION }}.tar.gz
